/* Generated By:JavaCC: Do not edit this line. Language20221Constants.java */
package classes;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Language20221Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_ALL = 16;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_AND = 17;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_AS = 18;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_AVALIATE = 19;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_BODY = 20;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_CONSTANT = 21;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_DECLARATION = 22;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_DESCRIPTION = 23;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_DESIGNATE = 24;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_DO = 25;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_INTEGER = 26;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_IS = 27;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_LOGIC = 28;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_READ = 29;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_REAL = 30;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_REPEAT = 31;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_RESULT = 32;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_STRING = 33;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_THIS = 34;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_TRUE = 35;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_TYPE = 36;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_UNTRUE = 37;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_VARIABLE = 38;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_WRITE = 39;
  /** RegularExpression Id. */
  int LETRA_MINUSCULA = 40;
  /** RegularExpression Id. */
  int LETRA_MAIUSCULA = 41;
  /** RegularExpression Id. */
  int LETRA = 42;
  /** RegularExpression Id. */
  int ASCII = 43;
  /** RegularExpression Id. */
  int DIGITO = 44;
  /** RegularExpression Id. */
  int UNDERLINE = 45;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 46;
  /** RegularExpression Id. */
  int IDENT1 = 47;
  /** RegularExpression Id. */
  int IDENT2 = 48;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL = 49;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_INTEIRA = 50;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_REAL_CASAS_DECIMAIS = 51;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_REAL = 52;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_ABRE_CHAVES = 53;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_FECHA_CHAVES = 54;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_PONTO_FINAL = 55;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_VIRGULA = 56;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_ABRE_COLCHETES = 57;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_FECHA_COLCHETES = 58;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_ABRE_PARENTESES = 59;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_FECHA_PARENTESES = 60;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_ADICAO = 61;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_SUBTRACAO = 62;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_MULTIPLICACAO = 63;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_DIVISAO = 64;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_POTENCIACAO = 65;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_DIVISAO_INTEIRA = 66;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_RESTO_DIVISAO_INTEIRA = 67;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_IGUAL = 68;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_DIFERENTE = 69;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_MENOR = 70;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_MAIOR = 71;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_MENOR_IGUAL = 72;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_MAIOR_IGUAL = 73;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_E = 74;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_OU = 75;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_NAO = 76;
  /** RegularExpression Id. */
  int SIMBOLO_INVALIDO = 77;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL_INVALIDA = 78;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_INTEIRA_INVALIDA = 79;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_REAL_INVALIDA = 80;
  /** RegularExpression Id. */
  int COMENTARIO_FACULTATIVO_INVALIDO = 81;
  /** RegularExpression Id. */
  int IDENTIFICADOR_INVALIDO = 82;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMENTARIO_BLOCO = 1;
  /** Lexical state. */
  int COMENTARIO_LINHA = 2;
  /** Lexical state. */
  int COMENTARIO_FACULTATIVO = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\r\\n\"",
    "\"\\n\\r\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\"//\"",
    "<token of kind 12>",
    "<token of kind 13>",
    "\"description\"",
    "<token of kind 15>",
    "\"all\"",
    "\"and\"",
    "\"as\"",
    "\"avaliate\"",
    "\"body\"",
    "\"constant\"",
    "\"declaration\"",
    "\"description\"",
    "\"designate\"",
    "\"do\"",
    "\"integer\"",
    "\"is\"",
    "\"logic\"",
    "\"read\"",
    "\"real\"",
    "\"repeat\"",
    "\"result\"",
    "\"string\"",
    "\"this\"",
    "\"true\"",
    "\"type\"",
    "\"untrue\"",
    "\"variable\"",
    "\"write\"",
    "<LETRA_MINUSCULA>",
    "<LETRA_MAIUSCULA>",
    "<LETRA>",
    "<ASCII>",
    "<DIGITO>",
    "\"_\"",
    "<IDENTIFICADOR>",
    "<IDENT1>",
    "<IDENT2>",
    "<CONSTANTE_LITERAL>",
    "<CONSTANTE_NUMERICA_INTEIRA>",
    "<CONSTANTE_NUMERICA_REAL_CASAS_DECIMAIS>",
    "<CONSTANTE_NUMERICA_REAL>",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"%%\"",
    "\"==\"",
    "\"!=\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<SIMBOLO_INVALIDO>",
    "<CONSTANTE_LITERAL_INVALIDA>",
    "<CONSTANTE_NUMERICA_INTEIRA_INVALIDA>",
    "<CONSTANTE_NUMERICA_REAL_INVALIDA>",
    "<COMENTARIO_FACULTATIVO_INVALIDO>",
    "<IDENTIFICADOR_INVALIDO>",
  };

}
