/* Generated By:JavaCC: Do not edit this line. Language20221Constants.java */
package classes;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Language20221Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_ALL = 8;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_AND = 9;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_AS = 10;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_AVALIATE = 11;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_BODY = 12;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_CONSTANT = 13;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_DECLARATION = 14;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_DESCRIPTION = 15;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_DESIGNATE = 16;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_DO = 17;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_INTEGER = 18;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_IS = 19;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_LOGIC = 20;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_READ = 21;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_REAL = 22;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_REPEAT = 23;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_RESULT = 24;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_STRING = 25;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_THIS = 26;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_TRUE = 27;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_TYPE = 28;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_UNTRUE = 29;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_VARIABLE = 30;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA_WRITE = 31;
  /** RegularExpression Id. */
  int LETRA_MINUSCULA = 32;
  /** RegularExpression Id. */
  int LETRA_MAIUSCULA = 33;
  /** RegularExpression Id. */
  int LETRA = 34;
  /** RegularExpression Id. */
  int ASCII = 35;
  /** RegularExpression Id. */
  int DIGITO = 36;
  /** RegularExpression Id. */
  int UNDERLINE = 37;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 38;
  /** RegularExpression Id. */
  int IDENT1 = 39;
  /** RegularExpression Id. */
  int IDENT2 = 40;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL = 41;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_INTEIRA = 42;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_REAL_CASAS_DECIMAIS = 43;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_REAL = 44;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_ABRE_CHAVES = 45;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_FECHA_CHAVES = 46;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_PONTO_FINAL = 47;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_VIRGULA = 48;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_ABRE_COLCHETES = 49;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_FECHA_COLCHETES = 50;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_ABRE_PARENTESES = 51;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL_FECHA_PARENTESES = 52;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_ADICAO = 53;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_SUBTRACAO = 54;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_MULTIPLICACAO = 55;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_DIVISAO = 56;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_POTENCIACAO = 57;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_DIVISAO_INTEIRA = 58;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_RESTO_DIVISAO_INTEIRA = 59;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_IGUAL = 60;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_DIFERENTE = 61;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_MENOR = 62;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_MAIOR = 63;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_MENOR_IGUAL = 64;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL_MAIOR_IGUAL = 65;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_E = 66;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_OU = 67;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_NAO = 68;
  /** RegularExpression Id. */
  int OPERADOR_ATRIBUICAO = 69;
  /** RegularExpression Id. */
  int SIMBOLO_INVALIDO = 70;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL_INVALIDA = 71;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_INTEIRA_INVALIDA = 72;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_REAL_INVALIDA = 73;
  /** RegularExpression Id. */
  int COMENTARIO_FACULTATIVO_INVALIDO = 74;
  /** RegularExpression Id. */
  int IDENTIFICADOR_INVALIDO = 75;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int BLOCK_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "<token of kind 4>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"all\"",
    "\"and\"",
    "\"as\"",
    "\"avaliate\"",
    "\"body\"",
    "\"constant\"",
    "\"declaration\"",
    "\"description\"",
    "\"designate\"",
    "\"do\"",
    "\"integer\"",
    "\"is\"",
    "\"logic\"",
    "\"read\"",
    "\"real\"",
    "\"repeat\"",
    "\"result\"",
    "\"string\"",
    "\"this\"",
    "\"true\"",
    "\"type\"",
    "\"untrue\"",
    "\"variable\"",
    "\"write\"",
    "<LETRA_MINUSCULA>",
    "<LETRA_MAIUSCULA>",
    "<LETRA>",
    "<ASCII>",
    "<DIGITO>",
    "\"_\"",
    "<IDENTIFICADOR>",
    "<IDENT1>",
    "<IDENT2>",
    "<CONSTANTE_LITERAL>",
    "<CONSTANTE_NUMERICA_INTEIRA>",
    "<CONSTANTE_NUMERICA_REAL_CASAS_DECIMAIS>",
    "<CONSTANTE_NUMERICA_REAL>",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"%%\"",
    "\"==\"",
    "\"!=\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"=\"",
    "<SIMBOLO_INVALIDO>",
    "<CONSTANTE_LITERAL_INVALIDA>",
    "<CONSTANTE_NUMERICA_INTEIRA_INVALIDA>",
    "<CONSTANTE_NUMERICA_REAL_INVALIDA>",
    "<COMENTARIO_FACULTATIVO_INVALIDO>",
    "<IDENTIFICADOR_INVALIDO>",
  };

}
